config/routes.rb
Blog::Application.routes.draw do
  

  resources :permissions

  get 'player/:player_id/actions' => 'actions#index', :as => :action
  get 'player/:player_id/actions/daily' => 'actions#daily', :as => :daily_action, :defaults => { :format => 'json' }
  get 'player/:player_id/actions/hour' => 'actions#hour', :as => :hour_action, :defaults => { :format => 'json' }
  resources :players

  get 'areas/dashboard' => 'areas#dashboard'
  resources :areas

  resources :portals

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  root :to => "home#index"

end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  load_and_authorize_resource
  def index
  	@player = Player.find(params[:player_id])
  	unless @player
  		flash[:notice] = "The player you were looking for could not be found."
    	redirect_to root_path
  	end
  end

  def daily
    actions = Action.byPlayer(params[:player_id])

    grouped_actions = {
      :deploy_ap => actions.collect{ |r| [ r.action_at.to_i*1000, r.deploy_ap.to_i ] } ,
      :destroy_ap => actions.collect{ |r| [ r.action_at.to_i*1000,  r.destroy_ap.to_i ] },
      :deployes => actions.collect{ |r| [ r.action_at.to_i*1000, r.deployes.to_i ]},
      :destroyes => actions.collect{ |r| [r.action_at.to_i*1000, r.destroyes.to_i ] },
      :usage_points => actions.collect{ |r| [ r.action_at.to_i*1000, r.destroyes.to_i + r.deployes.to_i] },
      :action_points => actions.collect{ |r| [ r.action_at.to_i*1000, r.destroy_ap.to_i + r.deploy_ap.to_i] }
    }

    @actions = grouped_actions.collect do |name, actions_by_type|
      {
        :name => name,
        :type => (name == :usage_points or name == :action_points) ? 'spline' : 'column',
        :data => actions_by_type
      }
    end
    respond_to do |format|
      format.json { render :json => @actions }
    end
  end

  def hour
    actions = Action.byPlayer(params[:player_id])
    hourly_actions = actions.group_by{ |r| r.action_at.strftime('%H').to_i}

    hourly = hourly_actions.to_a
      .collect{ |r| [ r[0], r[1].collect{|r| r.destroyes.to_i + r.deployes.to_i}.sum ] }
      .sort{ |a, b| a[0] <=> b[0] }

    respond_to do |format|
      format.json { render :json => hourly }
    end
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/views/actions/index.html.erb
<%- model_class = Action -%>
<div class="page-header">
  <h1><%= @player.name %> activity</h1>
</div>

<%= link_to '&laquo; Back to '.html_safe+ @player.name + ' profile', player_path(@player), :class => 'btn'%>

<% content_for :javascript do %>
<%= javascript_include_tag "actions" %>
<script>
$(function () {
        $.get('<%= daily_action_path(@player.id) %>', function(data){
            $('#dailyActivity').highcharts({
                title: { text: 'Daily activity' },
                xAxis: { type: 'datetime' },
                yAxis: {
                    title: { text: 'Amount actions and activity points' },
                    min: 0
                },
                tooltip: {
                    shared: true, crosshairs: true
                },
                series: data
            });
        })

        $.get('<%= hour_action_path(@player.id) %>', function(data){
            var four_hour_stat = {}, four_hour_data = []

            // Конвертируем почасовую статистику, в группы по 4 часа
            for(var i in data){
                var hour = Math.floor((data[i][0]) / 4)*4, activity = data[i][1];
                if( four_hour_stat[hour] ) four_hour_stat[hour][1] += activity
                else four_hour_stat[hour] = [ hour + " - " + (hour+4), activity ]
            }
            for (var i in four_hour_stat ) four_hour_data.push( four_hour_stat[i] )
            // Необходимо преобразовать к строке, иначе Highchart не понимает число
            for(var i in data) data[i][0] = data[i][0] + ''

            var hourSeries = [{
                center: [110, 100], size: 150,
                showInLegend: false, data: data
            }, {
                center: [410, 100], size: 150,
                showInLegend: false, data: four_hour_data
            }];

            $('#hourActivity').highcharts({
                chart: { type: 'pie' },
                title: { text: 'Hour activity' },
                
                tooltip: {
                    shared: true,
                    crosshairs: true,
                    formatter: function () {
                       return '<strong>'+this.key + '</strong><br>' + this.total + ' (' + Highcharts.numberFormat(this.percentage, 1)+ '%)';
                    }
                },
                series: hourSeries
            });
        });
        
    });
</script>
<% end %>

<div id="dailyActivity" style="min-width: 400px; height: 400px; margin: 0 auto"></div>
<div id="hourActivity" style="width: 600px; height: 300px; margin: 0 auto"></div>