config/routes.rb
Blog::Application.routes.draw do
  

  resources :permissions

  get 'player/:player_id/actions' => 'actions#index', :as => :action
  get 'player/:player_id/actions/daily' => 'actions#daily', :as => :daily_action, :defaults => { :format => 'json' }
  get 'player/:player_id/actions/hour' => 'actions#hour', :as => :hour_action, :defaults => { :format => 'json' }
  resources :players

  get 'areas/dashboard' => 'areas#dashboard'
  resources :areas

  resources :portals

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable#, :omniauth_providers => [:google_apps]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessor :accessible
  
  has_and_belongs_to_many :permissions, :join_table => :users_permissions
  belongs_to :player
  # attr_accessible :title, :body

  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token.info
	if user = User.where(:email => data["email"]).first
	  user
	else
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end
  
  private
  def mass_assignment_authorizer(role = :default)
    super + (accessible || [])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_filter :verify_authenticity_token, :only => [:google]

  def google
    @user = User.find_for_open_id(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource

	def index
		@users = User.all()
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.accessible = [:permission_ids] if can? :manage, User

		respond_to do |format|
			if @user.update_attributes(params[:user])
				format.html { redirect_to @user, notice: 'User was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field', :readonly => true %>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :permissions, :class => 'control-label' %>
    <div class="controls">
    		<% for permission in Permission.find(:all) %>
    				<label class="checkbox">
    					<%= check_box_tag "user[permission_ids][]", permission.id, @user.permissions.include?(permission) %>
    					<%= permission.name %>
    				</label>
    		<% end %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                permissions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email , user_path(user) %></td>
        <td><%= user.last_sign_in_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:id) %>:</strong></dt>
  <dd><%= @user.id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emal) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @user.created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:player) %>:</strong></dt>
  <% if @user.player %>
    <dd><%= link_to @user.player.name, player_path(@user.player) %></dd>
  <% else %>
    <dd>Not confirmed yet</dd>
  <% end %>
</dl>

<ul>
  <% @user.permissions.each do |permission| %>
    <li><strong><%= link_to permission.name, edit_permission_path(permission.id) %></strong> &mdash; :<%= permission.action %>, <%= permission.subject_class %><%= (', '+permission.subject_id.to_s) unless permission.subject_id.nil? || permission.subject_id == 0%></li>
  <% end %>
</ul>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <% if can? :manage, User %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <% end %>
</div>