config/routes.rb
Blog::Application.routes.draw do
  

  resources :permissions

  get 'player/:player_id/actions' => 'actions#index', :as => :action
  get 'player/:player_id/actions/daily' => 'actions#daily', :as => :daily_action, :defaults => { :format => 'json' }
  get 'player/:player_id/actions/hour' => 'actions#hour', :as => :hour_action, :defaults => { :format => 'json' }
  resources :players

  get 'areas/dashboard' => 'areas#dashboard'
  resources :areas

  resources :portals

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  root :to => "home#index"

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :comments, :fraction, :gplus, :level, :realname, :vk, :location, :phone, :transport
  def self.search(search)
  	if search
  		where('name LIKE ?', "%#{search}%")
  	else
  		scoped
  	end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  load_and_authorize_resource
  
  before_filter :authenticate_user!
  # GET /players
  # GET /players.json
  def index
    #@players = Player.order(:created_at).limit(10)
    @players = Player.search(params[:search]).order("name").paginate(:per_page => 10, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end


  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for @player, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', :readonly => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fraction, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fraction, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :level, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :level, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :realname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :realname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gplus, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :gplus, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vk, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vk, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :transport, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :transport, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comments, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :comments, :class => 'text_area', :rows => 8, :cols => 40 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                players_path, :class => 'btn' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/index.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= form_tag players_path, :method => 'get', :class => 'search' do %>
    <%= text_field_tag :search, params[:search], :class => "input-medium search-query" %>
    <%= submit_tag "Search", :name => nil, :class => 'btn' %>
<% end %>

<%= will_paginate @players %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:fraction) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:realname) %></th>
      <th><%= model_class.human_attribute_name(:comments) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.id, player_path(player) %></td>
        <td><%= link_to (player.name+"&nbsp;&raquo;").html_safe, action_path(player.id) %></td>
        <td><%= player.fraction %></td>
        <td><%= player.level %></td>
        <td><%= player.realname %></td>
        <td><%= player.comments %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_player_path(player), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/show.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

  <div class="pull-right">
    <% if @player.vk %>
      <a target="_blank" href="https://vk.com/<%= @player.vk %>"><%= image_tag 'habrapack/with_shadow/vk.png' %></a>
    <% end %>
    <% if @player.gplus %>
      <a target="_blank" href="https://plus.google.com/<%= @player.gplus %>"><%= image_tag 'habrapack/with_shadow/google_plus.png' %></a>
    <% end %>
  </div>
  
<h2 class="<%= @player.fraction == 'ALIENS' ? 'text-success' : 'text-info' %>">
  <%= @player.name %>
  <% if @player.level > 1 %>
    (<%= @player.level %>)
  <% end %>
  <% if @player.realname %>
    <sup>[<%= @player.realname %>]</sup>
  <% end %>
</h2>


  <% if can? :statistic, Player %>
    <%= link_to t('.edit', :default => t("helpers.links.activity")),
              action_path(@player.id), :class => 'btn btn-primary' %>
  <% end %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @player.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @player.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:transport) %>:</strong></dt>
  <dd><%= @player.transport %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comments) %>:</strong></dt>
  <dd><%= @player.comments %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              players_path, :class => 'btn'  %>
  <% if can? :manage, Player %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_player_path(@player), :class => 'btn' %>
  <% end %>
</div>