config/routes.rb
Blog::Application.routes.draw do
  

  resources :permissions

  get 'player/:player_id/actions' => 'actions#index', :as => :action
  get 'player/:player_id/actions/daily' => 'actions#daily', :as => :daily_action, :defaults => { :format => 'json' }
  get 'player/:player_id/actions/hour' => 'actions#hour', :as => :hour_action, :defaults => { :format => 'json' }
  resources :players

  get 'areas/dashboard' => 'areas#dashboard'
  resources :areas

  resources :portals

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ingress" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Ingress</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if can? :read, Player %>
                <li><%= link_to "Players", players_path  %></li>
              <% end %>
              <% if can? :manage, User %>
                <li><%= link_to "Users", users_path  %></li>
              <% end %>
              <% if can? :manage, Permission %>
                <li><%= link_to "Permissions", permissions_path  %></li>
              <% end %>
            </ul>
            <ul id="user_login_box" class="nav pull-right">
			<% if user_signed_in? -%>
			          <li><a href="#"><%= current_user.email %></a></li>
			          <li><%= link_to 'My info', edit_user_registration_path %></li>
			          <li class="divider-vertical"></li>
			          <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
			<% else -%>
				<li><%= link_to "sign in with google", user_omniauth_authorize_path(:google) %></li>
			<% end -%>
			</ul>
          </div><!--/.nav-collapse -->

	
			
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <!-- <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div>< !.well > -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>
  </body>
</html>